### ISSUE TITLE
deployment?

### ISSUE THREAD

**Issue by deepgray** [RPISEC/HackTheVote#2]
This was a great CTF...but is there a way to reproduce this in house via deployment scripts and the like?

**Comment by Lense** [comment]
Challenge directories should have subdirectories for what you need.

- `handout/` contains what was available to download during the CTF. For things like forensics, this might be all that you need.
- `setup/` contains a script to deploy the challenge on a clean AWS Ubuntu 16.04 LTS box.
- `src/` usually contains the source code for the challenge, if available.

We did not publish a big script that spins up all the AWS boxes and launches the challenges.

If there are issues about specific challenges, please file gh issues or join our [irc](https://rpis.ec/irc).
